export const MAP_VIEW_MIN_HEIGHT = 360;

export const MAP_ACTION_INSET = 20;
export const MAP_LOCATION_PROMPT_TOP = MAP_ACTION_INSET + 56 + 8;
export const MAP_RIGHT_CONTROLS_BOTTOM = MAP_ACTION_INSET + 76;
export const MAP_LAYER_ABOVE_LOCATE = 52;
export const MAP_ZOOM_CONTROLS_BOTTOM = MAP_RIGHT_CONTROLS_BOTTOM + MAP_LAYER_ABOVE_LOCATE + 40 + 8;

export const MAP_BOUNDS_DEBOUNCE_MS = 650;
export const MAP_QUERY_BOUNDS_PAD_FACTOR = 0.75;
export const MAP_QUERY_STALE_TIME_MS = 5 * 60_000;

export const MAP_LOCATION_PROMPT_DISMISSED_KEY = 'mapLocationPromptDismissed';
export const MAP_ACTION_BANNER_BOTTOM = MAP_ACTION_INSET + 112;
